export const weddingConfig = {
  coupleNames: 'Soumya & Sai Abhiram',
  subtitle:
    'With joyful hearts, we invite you to celebrate our Engagement, Haldi, Marriage, and Cocktail Party over three beautiful days of love, laughter, and togetherness.',
  datesLabel: 'May 7–9, 2026',
  cityLabel: 'Aubrey, Texas & Irving, Texas',
  heroPhotos: [
    '/photos/couple-1.jpg',
    '/photos/couple-2.jpg',
    '/photos/couple-3.jpg',
  ],
  events: [
    {
      id: 'engagement',
      title: 'Engagement',
      day: 'Day 1',
      time: '9:00 AM onwards',
      venue: 'The Bliss at Aubrey – Ranch House',
      note: 'Join us for a beautiful evening celebrating the beginning of our forever.',
      theme: 'rose',
      color: '#ff6b9d',
      backgroundImage: 'https://i.pinimg.com/originals/71/d7/e1/71d7e153f5b1ea803896a9494719d52d.jpg',
    },
    {
      id: 'haldi',
      title: 'Haldi',
      day: 'Day 2',
      time: '10:00 AM onwards',
      venue: 'The Bliss at Aubrey – Outdoors',
      note: 'A joyful Haldi ceremony filled with blessings, laughter, and color.',
      theme: 'haldi',
      color: '#ffd700',
      backgroundImage: 'https://i.pinimg.com/originals/c5/48/7f/c5487f67a9bc83f6983a218126e39048.jpg',
    },
    {
      id: 'marriage',
      title: 'Marriage',
      day: 'Day 3',
      time: '9:00 AM onwards',
      venue: 'The Prism at Irving',
      note: 'We would be honored to have you join us as we exchange vows.',
      theme: 'marriage',
      color: '#ff1493',
      backgroundImage: 'https://i.pinimg.com/originals/25/a2/c7/25a2c7dd7e2c168bc718fd719f172c8f.jpg',
    },
    {
      id: 'cocktail',
      title: 'Cocktail Party',
      day: 'Day 3',
      time: '8:00 PM onwards',
      venue: 'The Bliss at Aubrey – North Hall',
      note: 'Celebrate with us over music, dinner, and a memorable evening.',
      theme: 'cocktail',
      color: '#a78bfa',
      backgroundImage: 'https://i.pinimg.com/originals/b7/67/7d/b7677d0a5b16f15bc5a88d3b06fa3709.jpg',
    },
  ],
}

export const appsScriptUrl = import.meta.env.VITE_APPS_SCRIPT_URL || ''